### ISSUE TITLE
medpros link 

### ISSUE THREAD

**Issue by mgortega95** [ArchaicBubba/ArmyKnowledgeOffline#16]
hello, 
i need to access the medpros link. i need to schedule all my appts for my PHA and i can not access the medpros link to complete the first part.

**Comment by ArchaicBubba** [comment]
Currently MODS is down for the entire Army. This will effect most MEDPROS functions. AKOffline is unable to fix their servers as it is a third party site. Please wait for MODS to come back online. In the event that the MEDPROS link has become out of date due to the MODS maintenance it will be updated when MODS come back online.

**Comment by mgortega95** [comment]
Hello, Is there a time when this will be back up? Sent from my iPhoneOn Sep 23, 2024, at 4:55 PM, Roman Antonacci ***@***.***> wrote:﻿
Currently MODS is down for the entire Army. This will effect most MEDPROS functions. AKOffline is unable to fix their servers as it is a third party site. Please wait for MODS to come back online. In the event that the MEDPROS link has become out of date due to the MODS maintenance it will be updated when MODS come back online.

**Comment by ArchaicBubba** [comment]
I do not have any management or preview into the MODS system. I would recommend calling your installation's appointment hotline or the Army Service Desk as they may have more information.
